services:
  crewai:
    # image: python:3.12-slim
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - ./.env
    # entrypoint: